model_args:
  vocab_size: 256
  dim: 512
  v_dim_mult: 2
  ffn_mult: 3
  head: 4
  n_layers: 8
  context_len: 1024

lr: 3e-4
wd: 0.05
betas: [0.9, 0.98]
grad_norm_clip: 1.0
warm_up_steps: 100
step_limit: 1000

batch_size: 64
grad_accum_steps: 1
seed: 42
train_ratio: 0.9

device: cuda
dtype: bfloat16
compile: true
tf32: true
num_workers: 8
dataset_path: /ptmp/yinxu/LinearAttention/ds/tiny_shakespeare.txt

output_path: /ptmp/yinxu/LinearAttention/ckpt
experiment_name: transformer-smoke

save_interval: 500
valid_interval: 200
eval_batch_size: 64
valid_batches: 10
log_interval: 10
single_batch_test: false
